security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Max\LessonBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [in_memory, db]
        db:
            entity:
                class: Max\LessonBundle\Entity\User
                property: name
        in_memory:
            memory:
                users:
                    user:  { password: 123, roles: [ 'ROLE_USER' ] }
                    admin: { password: 123, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous:  ~
            form_login: ~
            logout:     ~
                # path:   logout
                # target: home
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        # - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
